name: Release Changeset

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: >-
            ${{ format('release: {0}', github.run_id) }}
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          # #gvs channel in One X Slack
          channel-id: ${{ vars.SLACK_RELEASE_BOT_CHANNEL_ID }}
          # For posting a simple plain text message
          slack-message: "<[${{ github.sha }}]|${{ github.event.head_commit.url }}>: A new version of ${{ github.repository }} was published! View release notes at https://github.com/${{ github.repository }}/releases."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_RELEASE_BOT_TOKEN }}

      - name: Publish Github Release from Tags
        # See: https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
